services:
  - type: web
    plan: free
    name: Filestreambot-pro
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m Adarsh
    repo: https://github.com/Greymattersbot/Filestreambot-pro.git      
    branch: main
    envVars:
      - key: API_ID 
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN 
        sync: false
      - key: OWNER_ID
        sync: false
      - key: OWNER_USERNAME
        sync: false
      - key: DATABASE_URL
        sync: false 
      - key: PICS
        sync: false
      - key: BIN_CHANNEL
        sync: false    
      - key: UPDATES_CHANNEL
        sync: false    
    autoDeploy: false
